### ISSUE TITLE
Including to Laravel 5.2

### ISSUE THREAD

**Issue by AratKruglik** [atomx/atomx-api-php#16]
Please, tell me how to include this package to project on Laravel 5.2?

**Comment by mrm** [comment]
Hi Arat, simply require the package using composer in your project:
```composer require atomx/atomx-api-php```

**Comment by AratKruglik** [comment]
And? How to use it after it? Need manual...

**Comment by erikdubbelboer** [comment]
@AratKruglik You can find more information about our API and how to use it on our wiki: https://wiki.atomx.com/api
